### ISSUE TITLE
Add plain and simple server upload instructions

### ISSUE THREAD

**Issue by sils** [fedora-infra/asknot-ng#40] opened 2015-08-15 19:11 UTC
When I upload the whole build directory to my server and redirect the URL to en/index.html weird things happen and it appears to not be able to find the bootstrap theme until I revert https://github.com/fedora-infra/asknot-ng/commit/81f975779a8f42cb1293fb542a093a09e7c6270e .

**Comment by ralphbean** [comment] 2015-08-15 19:53
As discussed in IRC, the issue is that a directory is now a symlink, so (if served under apache) you have to include "Options FollowSymLinks" inside the <Directory> entry in the apache config.

**Comment by sils** [comment] 2015-08-15 19:59
/me looks up if he's allowed to do that...

2015-08-15 21:53 GMT+02:00 Ralph Bean notifications@github.com:

**Comment by sils** [comment] 2015-08-15 20:06
I really need to switch... I'm not allowed to change that it seems. Would be nice if the stuff would work without needing to change restricted environments.

**Comment by ralphbean** [comment] 2015-08-15 20:22
Yes.  :/  There are hooks in the repo which should allow you to run somewhat painlessly in openshift, if that helps.

**Comment by sils** [comment] 2015-09-30 20:01
@ralphbean is there any workaround?

**Comment by sils** [comment] 2015-09-30 20:04
Ah replace the bootstrap symlink with the real directory. Anything against doing that in the real repo?

**Comment by ralphbean** [comment] 2015-09-30 20:12
no, that's fine.  go for it!

**Comment by Sadin** [comment] 2016-09-12 18:32
Closing if this is resolved.

**Closed as completed by Sadin** 2016-09-12 18:32 UTC
